---
- name: Install needed tools
  apt:
    name: ethtool

- name: Clone respondd announce repository
  git:
    repo: "{{ mesh_announce_git_root }}"
    dest: "/opt/{{ site_code }}/mesh-announce/"
    version: "{{ mesh_announce_git_commit }}"
  notify:
    - restart respondd

- name: Install system unit
  template:
    src: service
    dest: /etc/systemd/system/respondd.service
  notify:
    - reload systemd
    - restart respondd

- name: Enable respondd
  service:
    name: respondd
    enabled: yes

- name: Install timer
  import_role:
    name: timer
  vars:
    timer_name: mesh-announce
    timer_exec: "/opt/{{ site_code }}/mesh-announce/announce.sh -i {{ alfred_mtu_interface if alfred_master else main_bridge }} -b {{ batman_interface }}"
    timer_interval: 1min
  when: mesh_announce_alfred

- name: Remove legacy cronjob
  file:
    path: /etc/cron.d/mesh-announce-alfred
    state: absent

- name: Open firewall for respondd
  template:
    src: firewall.sh
    dest: "{{ firewall_path }}/30-respondd"
  when: firewall_enabled
  notify: reload firewall
